#!/bin/bash
show_help(){
    echo '
    Why Hello there! You must be looking for help
    
    The Flags: 

    r - run all

    a - create all
    
    s - stop particular Container
    
    n - new particular container 

    c - start particular container

    m - run bash for mysql container

    x - dont run this unless docker is f-ed

    p - like a phoenix from the ashes

    h - Dunno. Run and find out.

    Chain em together as you see fit 
    '
}

run(){
    mysql
    hhvm
    nginx
}

use(){
    CONTAINER="$1"
    V=`version`    
}

nginx(){

    # Silently kill
    docker stop nginx>/dev/null 2>/dev/null
    docker rm nginx>/dev/null 2>/dev/null

    CONTAINER="server"
    V=`version`
    echo "Starting Nginx Container: $(docker run -d -p 80:80 --name nginx $FLAGS \
        -v `pwd`/sites:/static:rw \
        -v `pwd`/server/sites-enabled:/etc/nginx/sites-enabled:rw $CONTAINER:$V /bin/server)"

}

mysql(){

    # Persistant data
    DB=persist
    docker volume create --name $DB

    # Silently kill
    docker stop mysql>/dev/null 2>/dev/null
    docker rm mysql>/dev/null 2>/dev/null

    use database
    echo "Starting Mysql Container: $(docker run -dit --name mysql -v $DB:/var/lib/mysql:rw $CONTAINER:$V /bin/run.sh)"; 

    #/bin/bash)"; 
}

webcontainer(){

    chmod -R 777 sites/scripts
    # Silently kill
    docker stop $1 >/dev/null 2>/dev/null
    docker rm $1 >/dev/null 2>/dev/null
    # echo "docker run -d --name $1 $EXTRA --link mysql:mysql -v `pwd`/sites/$1:/sites:rw $CONTAINER:$V /scripts/$1.sh";
    echo "Starting Hiphop $1 Container: $(docker run -d --name $1 $EXTRA --link mysql:mysql -v `pwd`/sites/$1:/sites:rw $CONTAINER:$V /scripts/$1.sh)"
    EXTRA=
    chmod -R 000 sites/scripts
}

injection(){
    FLAGS="$FLAGS \
        --link injection:injection"   
    use sites
    webcontainer injection
}

serverside(){
    FLAGS="$FLAGS --link serverside:serverside"
    
    use sites
    webcontainer serverside
}

gitlist(){
    FLAGS="$FLAGS \
        --link gitlist:gitlist"
    use sites
    webcontainer gitlist
}

chuck(){
    FLAGS="$FLAGS --link chuck:chuck"
    EXTRA="-p 7331:7331"
    use sites
    webcontainer chuck
}

dashboard(){
    FLAGS="$FLAGS \
        --link dashboard:dashboard"
    use sites
    webcontainer dashboard
}

blog(){
    FLAGS="$FLAGS \
        --link blog:blog"
    use sites
    webcontainer blog
}

hhvm(){
    
    FLAGS=""
    injection
    serverside
    dashboard
    chuck
    gitlist
    blog

}

version(){
    if [[ "$CONTAINER" == "sites" || "$CONTAINER" == "server" || "$CONTAINER" == "database" ]]
    then
        docker images | grep -o "$CONTAINER\s*[0-9]*" -m 1 | grep -o [0-9]* || echo 1
        return
    fi
    echo "invalid container: $CONTAINER"
    exit 1
}

sites(){
    CONTAINER="sites"
    V=$((`version` + 1))
    cd sites
    docker build -t sites:$V . 
    cd ..
}

database(){
    CONTAINER="database"
    V=$((`version` + 1))
    cd database
    docker build -t database:$V . 
    cd ..
}

server(){
    CONTAINER="server"
    V=$((`version` + 1))
    cd server
    docker build -t server:$V . 
    cd ..
}

prompt(){
    printf "\nChoose a container...\nCTRL+C to exit:\n"
    select create in sites server database
    do
        # bash reflection say what?
        eval "$create" || exit 1
        exit 0
    done

}

stop(){
    printf "\nStop a container...\n"
    select stop in sites server database
    do
        docker stop $(docker ps | grep -o ".*\s$stop:" | grep -o '\([0-9a-f]\)\{12\}')
    done
}

contain(){
    printf "\Run image...\nCTRL+C to exit:\n"
    select image in injection serverside requests nginx mysql
    do
        # bash reflection say what?
        eval "$image" || exit 1

    done
}

die(){
    echo "Killing..."
    docker stop $(docker ps | grep -o ".*\s" | grep -o '\([0-9a-f]\)\{12\}')
    echo "------------"
}

all(){

    sites\
    && server\
    && database

}

fuckitall(){

    docker stop $(docker ps -a -q)
    docker rm   $(docker ps -a -q)
    docker rmi  $(docker images -a -q)
    docker volume rm persist;

}

phoenix(){

    fuckitall
    all

}

CONTAINER="sites"
V=`version`
while getopts "h?rnsdiklcxoampv:" opt; do
    case "$opt" in
    h|\?)
        show_help
        ;;
    r)  run
        ;;
    v)  CONTAINER="$OPTARG";echo "`version`";
        ;;
    n)  prompt
        ;;
    s)  stop
        ;;
    k)  die
        ;;
    x)  fuckitall
        ;;
    m)  db
        ;;
    c)  contain
        ;;
    p)  phoenix # just ran out of letters at this point
        ;;
    a)  all
        ;;
    esac
done

exit 0
