grant select on jokes.* to thenorris@'%' identified by 'cowboyF@ce' with grant option; 

/* Posts Table */
DROP TABLE IF EXISTS `jokes`;
CREATE TABLE `jokes` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `joke` longtext COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

/* Seed */
LOCK TABLES `jokes` WRITE;

INSERT INTO `jokes` VALUES 
(NULL,'Contrary to popular belief Chuck Norris, not the Florida Supreme Court, made the final judgement on Terri Schiavos fate. It was a roundhouse kick to the feeding tube.'),
(NULL,'A mighty crack was heard around the world as Chuck Norris roundhouse kicked the supercontinent, Pangaea, beginning continental drift.'),
(NULL,'Chuck Norris doesnt understand why you should consult your doctor if your erection lasts for more than 4 hours. His erections have been known to last for up to 15 days.'),
(NULL,'Chuck Norris doesnt look at the toilet paper after he wipes.'),
(NULL,'Chuck Norris throws midgets for fun. He used to do it competitively, but it all ended horribly when he killed the pope.'),
(NULL,'Someone once tried to assassinate Chuck Norriss beard but missed hitting Chuck in the face, Chuck proceeded to beat the holy hell out of the guy using nothing but his penis and elbow, Chuck has since installed security on his beard, with a deflector diverting bullets to his face, since he values his beard more than even his rugged good looks.'),
(NULL,'Chuck Norris can kill a dog in 7 ways, 4 of which involve throwing missiles at it.'),
(NULL,'Chuck Norris once went to jail. The morning after his first night all the inmates, all the guards, and the warden had bleeding assholes.'),
(NULL,'Chuck Norris lucky number is one, becuase thats how many tries it takes him to accomplish any task.'),
(NULL,'If you ever get the chance to play Chuck Norris in Madden football, he will beat you 56-7.'),
(NULL,'Chuck Norris refers to himself in fourth person.'),
(NULL,'Chuck Norris told that one kid from the Sixth Sense that he has AIDS. He then smiled.'),
(NULL,'Artificial insemination was invented when, during an intense and vigorous masturbation session, Chuck Norris high velocity ejaculate penetrated a womans vagina from a quarter of a mile away.  '),
(NULL,'Chuck Norris once killed a man with his bare hands. He then revived him with his bare hands only to end his life with a roundhouse kick to the face.'),
(NULL,'Chuck Norris killed Mcgyver by making a set of nun-chucks using newspaper, two toothpicks, a womans weave, and a 3 legged dog.'),
(NULL,'Chuck Norris penis is so large, that he in fact has to tie it around his left leg so that it doesnt get in the way of his round-house kick.'),
(NULL,'Chuck Norris once leaned against a tower in Pisa, Italy.'),
(NULL,'Chuck Norris can juggle 12 bar stools when drunk but only 8 when sober.'),
(NULL,'chuck norris invented racism because he thought the world was filled with '),
(NULL,'Chuck Norris once ate a bad cheese burger at McDonalds. So he tracked down the president of the company, and round house kicked his secretary in the face so hard that she released her bowels onto the office floor. He then force fed the McDolands president the entire mess. This meal is now considered a delicacy in certain parts of the world, and can be found in certain McDonalds establishments under the name '),
(NULL,'There was once a line of soap based off of Chuck Norris. His face was on every bar. While popular in the early 90s, the soap was discontinued after thousands of women started growing his stern yet sexy beard.'),
(NULL,'Chuck Norris built the equator to get a leg up on Chinas '),
(NULL,'In an attempt to follow in the steps of Dolly Parton, Chuck Norris attempted to open a theme park. Unfortunetly the idea was cast asunder when the name '),
(NULL,'There are three ways to do things. The right way, the wrong way and the Chuck Norris way. The Chuck Norris way is just the wrong way but with more roundhouse kicks.'),
(NULL,'Chuck has 5 letters. Norris has 6. When placed together we get 56. 1956 was the year of the first airborn nuclear test. Coincidence? I think not.'),
(NULL,'Chuck Norris invented death just so he could kill people.'),
(NULL,'Before Chuck Norris, it used to take the Earth 365 days to revolve around the sun. Then in the fall of 1976, Chuck Norris performed a roundhouse kick so powerful, the shockwave caused the Earth to slow and since then it now takes the Earth 365 and 1/4 days to revolve around the sun. Chuck Norris is the reason we recognize leap years.'),
(NULL,'The LA riots where not caused by the Rodney King verdict, they were actually started when Chuck Norris let the '),
(NULL,'Chuck Norris created the Total Gym by physically beating a Ford Pinto into the shape he had in his mind.  The gas tank did explode during the procedure, but not so much as one hair of Chuck Norriss beard was singed.'),
(NULL,'To keep is his mind sharp Chuck Norris plays Tic-Tac-Toe versus himself. He wins every time.'),
(NULL,'Chuck Norris wore jeans so tight his wife became sterile.'),
(NULL,'Chuck Norris was on a season of Survivor once, but the entire season got cut after Chuck Norris murdered everyone on the island for eating his Cheetos.'),
(NULL,'Chuck Norris occasionally has Missing In Action flashbacks where hes escaping a Vietnam Prison and randomly starts killing Asians with his bare fist because thats the way Chuck rolls. Youll know when its coming because Asians start flying through the air with random explosions, horrible subtitles will scroll your line of vision, and  Chuck will run and hide in your moms garden, finally stealing your Kia Sportage screaming, '),
(NULL,'When asked his opinion about the war in Iraq, Chuck Norris said '),
(NULL,'Someone once approached Chuck Norris suggesting that rearranging the letters in his name reveals the message '),
(NULL,'Chuck Norris once crushed a school bus full of children with his forehead.'),
(NULL,'Chuck Norris always keeps a Werthers Original in his jean pocket... For the kids.'),
(NULL,'Chuck Norris was playing Tekken 5 one day and finally met his match. His 12-year old son beat him with Eddy Gordo by randomly pressing buttons. Chuck Norris then roundhouse kicked his son in the throat killing him instantly. That night Chuck Norris ate well... He ate well indeed...'),
(NULL,'Chuck Norris is how the West was won.'),
(NULL,'Jupiters Great Red Spot isnt a storm. Its where Chuck Norris puts his victims.'),
(NULL,'Chuck Norris eats Viagra only so that he can have an extra loaded weapon on him at all times.'),
(NULL,'Chuck Norris was once held prisoner back in Nam. Chuck plucked a hair from his beard, picked a booger and combined them together to create a grenade launcher and killed every soldier in the prison. Once he was back in America he told his story at a bar. A desperate producer overheard his story and a light bulb lit up in his head. That night MacGyver was born.'),
(NULL,'Chuck Norris found Nemo.'),
(NULL,'Chuck Norris shot at 50 Cent 9 times, but didnt finsh him because he wanted to do it with a roundhouse kick to the face. But 50 Cent ran in horror.'),
(NULL,'Chuck Norris once juggled a soccer ball 2,357 times... with just his penis.'),
(NULL,'Chuck Norris can travel through time by running at 88 miles per hour.'),
(NULL,'Chuck Norris once roundhouse kicked a man into next week. He then roundhouse kicked himself into next week, so he could roundhouse the man another week forward.'),
(NULL,'Chuck Norris family crest is a picture of a baracudda eating Neil Armstrong.'),
(NULL,'Few people are aware that Chuck Norris is the first person to ever be diagnosed with beard cancer. Upon hearing this, Chuck Norris quickly beat the cancer into remission with a series of roundhouse kicks and rabbit punches.'),
(NULL,'Not many people know this but, Walker - Texas Ranger is actually a hidden camera show on Chuck Norriss life.'),
(NULL,'Congress is in the process of passing a bill to clone Chuck Norris for military purposes. They want his genes, particularly because Chuck Norris eyes offer nightvision and 3x zoom capabilities.'),
(NULL,'Chuck Norris actually invented peanut butter, but while in transit to the patent office, George Washington Carver knocked him unconscious with the aid of chloroform and stole his patent. For revenge, Chuck Norris threw 7 freight trains on top of George Washington Carver. He died from this.'),
(NULL,'Chuck Norris is ranked 12th in the AP college football poll.'),
(NULL,'If an EMP were to go off within a close proximity of Chuck Norris, he would be rendered useless for a short period of time, because over 500 years ago, he traded the ability to see the future to Nostradamus for cybernetic arms, legs, and heart.'),
(NULL,'Chuck Norris tought everyone in Texas karate, so it would look cooler when he kicked their ass on TV.'),
(NULL,'Everyone respects Chuck Norris so much, that when they fight him, they politely wait in turn for him to beat them up.'),
(NULL,'Chuck Norris once broke the kneck of a passing stranger in the street. When asked why he responded, '),
(NULL,'One day Chuck Norris was infact killed when he round house kicked someone in the face so hard that it shattered the universe. But in heaven, Chuck challenged God to an arm wrestling match. Chuck won, and the universe was reformed.'),
(NULL,'Chuck Norris once boned the Mona Lisa, which is why she smiles.'),
(NULL,'If you knock three times on a wooden object and shout the name of Chuck Norris with a lisp on your voice, he will appear to you and personally kick your ass. And it will be better than any orgasm you will ever experience.'),
(NULL,'Chuck Norris auditioned for the role of Albus Dumbledore for the movie '),
(NULL,'Chuck Norris once passed a kidney stone the size of a baseball. The stone is on display as a moon rock at NASA.'),
(NULL,'Chuck Norris stole your bike.'),
(NULL,'Chuck Norris believes strongly in ending world hunger. He plans to do this by terminating the populations of all third world countries.'),
(NULL,'Chuck Norris is actually the love child of Willie Nelson and an mystical ninja mummy.'),
(NULL,'A ducks quack does not echo. Chuck Norris is solely responsible for this phenomenon. When asked why he will simply stare at your grimly.'),
(NULL,'Hellen Kellers favorite color is Chuck Norris.'),
(NULL,'In an attempt to bolster ratings during sweeps week in 1988, CNN began referring to itself as the '),
(NULL,'It is Chuck Norris eye that adorns the Great Seal on the back of the $1 bill. He is all seeing.'),
(NULL,'Ask not what Chuck Norris will do for a Klondike bar, ask what the Klondike bar will do for Chuck Norris.'),
(NULL,'Chuck Norris is both blessed and cursed with the ability to destroy anything by merely by looking at it. To prevent this from happening, Chuck personally removed his eyes and now uses Bob Saget as the stick blind persons use to locate objects in their path. He can also use incredibly high pitched Karate screams as sonar.'),
(NULL,'The shadow from Chuck Norris mustache can accurately predict the length of winter to within 4 seconds. The groundhog has been rendered obsolete.'),
(NULL,'On the sixth day God created Chuck Norris.'),
(NULL,'Contrary to popular belief, Chuck Norris was dropped at Hiroshima and Nagasaki.'),
(NULL,'Chuck Norris does not see dead people. He eats them.'),
(NULL,'Chuck Norris and Steven Seagal are secretly married. Norris wears the pants.'),
(NULL,'Walker Texas Ranger is just a normal man, but when danger calls he transforms into Chuck Norris.'),
(NULL,'Chuck Norris was taking and evening stroll in a local neighborhood when a mountain spring water truck slammed in to a retarded child playing in the street. Chuck Norris rushed to the scene, destroyed the driver, and resurrected the child making him normal again. This event is celebrated as a show on TV called Captian Planet.'),
(NULL,'Chuck Norris was once accused of heresy by the Pope, but as it turns out, Chuck Norris is, in fact, the true son of god.'),
(NULL,'Chuck Norris is so awesome, he made the Bob Saget fact generator cease to exist. '),
(NULL,'Chuck Norris heart beats once every week.'),
(NULL,'One time Chuck Norris got bored so he flew to England and orally sodomized the entire royal family.'),
(NULL,'The original theme song to the Transformers was actually '),
(NULL,'Chuck Norris was the first person to climb Mount Everest. Naked.'),
(NULL,'One day Chuck Norris went shopping and he had grabbed the last can of pea soup off the counter. Just then Steven Segal, Jean-Claude Van Damme, and Godzilla walked in and turned to Chuck Norris and said, '),
(NULL,'Chuck Norris spread the belief that women do not take shits... I believe him.'),
(NULL,'Chuck Norris goes to the toilet once a month, if he needs to or not.'),
(NULL,'Chuck Norris once fed a starving Ethiopian boy a 12 course meal, then promptly sacrificed the boy to Satan in an effort to boost the ratings of Walker Texas Ranger.'),
(NULL,'Chuck Norris is the worlds best actor because his moustache is  the worlds best acting coach.'),
(NULL,'Chuck Norris once made love to a Sasquatch. This resulted in the birth of George W. Bush, and the Sasquatch contacting an incurable form of Syphillis, known as '),
(NULL,'Chuck Norris has every copy of National Geographic in his basement. He also has the ability to lift every single one of them at once.'),
(NULL,'In his spare time, Chuck Norris breeds thoroughbred horses by manually inseminating the females with his own semen.'),
(NULL,'Chuck Norris once injested Pop Rocks while drinking Coke, and lived to tell about it. He then proceeded to bitch slap the Pope for saying how much Walker Texas Ranger sucked.'),
(NULL,'Theres no such thing as a tornado. Chuck Norris just hates trailer parks.'),
(NULL,'To Chuck Norris, doorknobs and urination are seen as merely suggestions.'),
(NULL,'Chuck Norris can piss on the third rail and not get electrocuted.'),
(NULL,'Whereas most people are killed by a BAC of .45, Chuck Norris only passes out when the alcohol in his veins is less than 5% blood.'),
(NULL,'In response to his challenge, Chuck Norris roundhouse kicked MC Hammer so hard that he went bankrupt. Chuch Norris then bellowed, '),
(NULL,'Chuck Norris once tamed a wild stallion in the forest. He rode the horse across the United States and back in under 24 hours. When he returned home he killed the horse and ate the entire thing.'),
(NULL,'When he was a baby, Chuck Norris dropped his mother on her head. She never refused her breast milk to him again.'),
(NULL,'Chuck Norris loves cute little puppies. He especially loves them on rye with some pepper jack and a dash of paprika.'),
(NULL,'Chuck Norris once held an anti-government protest in Washington. At the news, the government was so terrified that it disbanded immediately and declared Chuck the new President. Though pleased, Chucks only intent had been to lure in dirty hippies to kick their asses.'),
(NULL,'Chuck Norris first appeared on TV when he was 8 years old, doing a musical number on the show Star Search.  When Chuck Norris musical number started he just roundhouse kicked one of the judges in the face.  He then remained motionless for the last two minutes of the song while smiling and giving the thumbs up.  Chuck Norris would have won but, due to paralysis, judge number three just made gurgling noises when he tried to tell Chuck Norris he received a perfect score.'),
(NULL,'When Chuck Norris was interviewed by local papers as to why he saved the baby from the fire he replied, '),
(NULL,'The Ice Age is contributed to Chuck Norris, that was the date of his last erection which blocked the suns rays for 47 years.'),
(NULL,'Vin Diesel has only had one nightmare in his lifetime. It involved Chuck Norris, and his murderous group of Oompa-Loompas.'),
(NULL,'Chuck Norris cannot be seen without 4-D vision glasses. His beard requires 5-D vision glasses and sun screen.'),
(NULL,'Chuck Norris never showers... because he never breaks a sweat.'),
(NULL,'An entire episode of Walker, Texas Ranger was shot with the lens cap on. This made no difference, however, because the light emanating from Chuck Norris beard permeated the plastic cap and allowed the camera to see Chuck in all his glory.'),
(NULL,'Chuck Norris circumcised himself. At birth. With his bare hands.'),
(NULL,'Chuck Norris ties dead puppies to his feet to simulate real blood spraying from the faces of his stunt actors.'),
(NULL,'Chuck Norris went to a fortune teller once. She predicted pain.'),
(NULL,'Chuck Norris once flushed himself down a toilet to fight an allegator. After defeating the beast with one swift round house kick, he went home to eat his neighbors children.'),
(NULL,'Chuck Norris was the first human to willingly snort anthrax, all he did was sneeze and out came Steven Seagal and Jet Li.'),
(NULL,'Chuck Norris doesnt experience miricales, he makes them.'),
(NULL,'Chuck Norris appeared in the movie Pearl Harbor in a cameo role as a palm tree. An ass-kicking, fire-breathing palm tree. Most of his scenes were cut, due to time and credibility restraints, since nobody could believe that Chuck could be within 500 yards of Ben Affleck without doing him serious bodily harm.'),
(NULL,'Once Chuck Norris made Jean Claude Van-Damme cry just by staring at him.'),
(NULL,'When asked if videogame-related violence was a threat to Americas children, Chuck Norris promptly roundhouse kicked Jack Thompson in the face. Ironically, moments later two 13-year-olds were found dead less than a mile from the scene, attempting to reenact this stunt.'),
(NULL,'Chuck Norris eats tiger hearts every morning for strength, power, and wisdom. He eates mens hearts for sport.'),
(NULL,'The the Geneva Convention specifically forbids the use of Chuck Norris in an international conflict.'),
(NULL,'Chuck Norris knows Steven Segall personally. He is made up of the corn in Chuck Norris fecal matter.'),
(NULL,'Booze gains alcohol content after passing through Chuck Norris.'),
(NULL,'Chuck Norris CAN find a needle in a haystack, and then kill a man with the needle... or the haystack.'),
(NULL,'Chuck Norris was once taking a dump in a public bathroom in New York, and at one point, the man in the next stall made a comment about the horrible stench of Chucks feces. Norris proceeded to release a bout of flatulence that incinerated the poor fool shitting next to him, and then recounted his story to a scientist friend of his, who did some further research. The basis for the atom bomb was discovered, and the research was called '),
(NULL,'Each year, Chuck Norris brings gifts to people across the world as compensation for killing one of their loved ones. We know this day as Christmas.'),
(NULL,'Chuck Norris has 118,453 friends on myspace. It is an unspoken agreement that when you join his list of friends, you are actually placing your name on his list of death, but Chuck Norris friends do not care. To die by the hand of Chuck is an honor.'),
(NULL,'Chuck Norris is the only man to never use an eraser.'),
(NULL,'Chuck Norris hates internet piracy but he also loves his fans. If he ever catches you downloading episodes of Walker: Texas Ranger, his conflicting opinions mean that he has to shake your hand and beat you senseless at the same time.'),
(NULL,'Tony Danza reports to Chuck Norris.'),
(NULL,'Chuck Norris constructed his own iPod by staring intensely at 10,000 country-western bands until they fearfully compacted themselves into a 2x4x1/2 inch white rectangle.'),
(NULL,'Why did the chicken cross the road? Because Chuck Norris ate its entire family, killed the farmer who bred it, and sex with the famers wife all at the same time.'),
(NULL,'Rumors falsely claim that b29 bombers dropped the atom bombs on Japan. The truth is that Chuck Norris threw the bomb all the way to Hirosima.'),
(NULL,'Due to the excessive amount of unprotected sex Chuck Norris takes part in, it is garunteed that he appears in your family tree anywhere from 3 to 10 times.'),
(NULL,'Chuck Norris is so cool that the Pope has a Jesus fish on his car with the word '),
(NULL,'Chuck Norris knows where in the world Carmen Sandiego is, but he wont tell because he doesnt want anyone to find the body.'),
(NULL,'Chuck Norris knows all the numbers of pi, but will only share them if he can be beaten in hand-to-hand combat. This is why we have supercomputers trying to figure it out instead.'),
(NULL,'Upon hearing of the possible outbreak of Bird Flu, Chuck Norris became outraged and announced he will kill off every species of bird. When asked about his statement, he replied, '),
(NULL,'Chuck Norris once beat Mike Tysons Punch Out in the desert while trimming red hair from his taint with a box cutter. What? You say there are no outlets for the Nintendo in the desert? Tell that to Chuck Norris.'),
(NULL,'The only person that can kill Chuck Norris is Chuck Norris. He is waiting until he runs out of other people to kill.'),
(NULL,'Chuck Norris will never '),
(NULL,'It is a commonly held belief of the Jewish faith that, as a mere babe, Chuck Norris was separated from his mother in a blizzard. To this day, he hates snow so much that he roundhouse kicks each individual snowflake. The concussive force makes them all unique.'),
(NULL,'Chuck Norris was recently credited with finding a new race of people living in his chest hair.'),
(NULL,'The Fantastic 4 was originally The Fantastic 5 until Chuck Norris was kicked out for raping the Invisible Woman.'),
(NULL,'Chuck Norris doesnt need oxygen. He only inhales in order to absorb the ashes of his enemies in his lungs. And exhaling? Thats because he doesnt want to shit.'),
(NULL,'One time a bee tried to sting Chuck Norris. He just laughed at it and blew it up with his laser vision.'),
(NULL,'Chuck Norris listens to Pantera to calm down.'),
(NULL,'Chuck Norris sperm can penetrate 13 condoms, the birth control pill, a brick wall, and the 1975 Pittsburgh Steelers offensive line in order to impregnate a woman.'),
(NULL,'God is Chuck Norris prototype.'),
(NULL,'Chuck Norris can read every AIM conversation for they are stored on the infinite hard drive of his computer.'),
(NULL,'Chuck Norris embodies the only matter known to have escaped a black hole.'),
(NULL,'Chuck Norris Blood Alcohol Level is continously 8.0, but he is always fine to drive.'),
(NULL,'Chuck Norris burned his eyeballs out with cigartettes just to prove to some grade eight students that smoking is dangerous.'),
(NULL,'The tide rises when Chuck Norris tells it to.'),
(NULL,'Stores will accept Monopoly money if Chuck Norris is paying.'),
(NULL,'Chuck Norris laugh sounds like that of a small child. You wouldnt know this because he never laughs.'),
(NULL,'Jimmy Hoffa is alive and well in Chuck Norris large intestine but refuses to say '),
(NULL,'Chuck Norris does not get frostbite. Chuck Norris bites frost.'),
(NULL,'Chuck Norris was once fined $1,000 for drawing Native American war symbols in invisible ink on the canvases of the Metropolitan Museum of Arts Impressionist wing.'),
(NULL,'Chuck Norris created whiskey to help control the Indians.'),
(NULL,'Oxygen requires Chuck Norris to live.'),
(NULL,'Chuck Norris once had a head on collision with the sun. Luckily, the sun is so far away that the shift of its position had no effect on Earth.'),
(NULL,'Chuck Norris has actually visited the moon on four separate occasions, each time saving Mars by jump kicking through the windscreen of communist shuttles and punching Stalin clones in the ovaries.'),
(NULL,'If you want to wear the same cologne as Chuck Norris, youll be disappointed to find that Chuck Norris doesnt wear cologne. For two hundred dollars, however, Mr. Norris will fart on your chest before you go on a date.'),
(NULL,'Some people believe UFOs fly around so erratically because they are trying to impress us. However, they are just trying to get away from Chuck Norris. The crash of 1947 showed the aliens that Earth would not be so easy to subdue.'),
(NULL,'Chuck Norris plays marbles with grenades.'),
(NULL,'Chuck Norris requires no stunt double, however his beard has stood in for the actor that played Chewbacca on many occasions.'),
(NULL,'Chuck Norris bones cannot be broken by anyone except Chuck Norris. Sometimes Chuck breaks his own bones just to show off.'),
(NULL,'Cars were invented to have a faster way of fleeing from Chuck Norris. Not to be outdone, Chuck Norris invented the car accident.'),
(NULL,'In order to shave, Chuck Norris would need a special razor made out of adamantium. The economic decline of the Carter administration caused the manufacturing of these razors to be too expensive, hence Chuck Norris now wears a beard.'),
(NULL,'The last person to challenge Chuck Norris to a hand-to-hand combat later became to founder of War-Amps.'),
(NULL,'Chuck Norris killed Rudolph, Donner, and Blitzen because they didnt join in any reindeer games.'),
(NULL,'Praying Mantises take after Chuck Norris. After having sex they bite off the head of their mate.'),
(NULL,'Chuck Norris was born a blonde, but the blood of his victims dyed his hair and beard to a healthy orange.'),
(NULL,'NASA hired Chuck Norris to save money. He kicks people into outer space, and they later land safely into his chest hair.'),
(NULL,'Chuck Norris removed his own tonsils. He didnt even have tonsillitis.'),
(NULL,'For every hour a plane ride takes, Chuck Norris can get to the destination in that many steps.'),
(NULL,'Lance Armstrong really didnt lose a testicle to cancer, he is actually the only living survivor to a Chuck Norris delivered round house kick to the balls'),
(NULL,'Chuck Norris once drank so much beer, all of the breweries of the world ran out. And then he started on wine...'),
(NULL,'When Chuck Norris enters a night club, he instantly becomes the life of the party. An instant is roughly how long it takes Chuck Norris to kill a room full of people.'),
(NULL,'Chuck Norris does not query the existence of God. God wonders if Chuck Norris is human, because he sure as hell never created him.'),
(NULL,'Chuck Norris once saved 500 people from a burning building in 0.3 seconds. He then proceeded to give each one a fatal round-house kick to the face.'),
(NULL,'Chuck Norris once dug his way to the center of the Earth using only a jar of petroleum jelly and his penis.'),
(NULL,'Chuck Norris created the first perpetual motion machine by hanging a Volkswagen Beetle on the end of a tetherball pole then kicking it. Thus he solved the worlds energy problem.'),
(NULL,'Chuck Norris melts dry ice in his pool so he can swim without getting wet.'),
(NULL,'Chuck Norris was called to the set of the movie '),
(NULL,'At this very moment, there is a 50/50 chance that Chuck Norris is boning your sister.'),
(NULL,'Chuck Norris once took 12 NoDoz pills and then slept for 48 straight hours, just to prove a point.'),
(NULL,'Chuck Norris used his bare hands and caught the Road Runner. He then roundhouse kicked Wile E. Coyote for being so incompetent.'),
(NULL,'When Chuck Norris found out dolphins were becoming an endangered species, he banged flipper and she gave birth 100 times.'),
(NULL,'Florida used to be in a straight line, until Chuck Norris kicked Miami for refusing to make a '),
(NULL,'Chuck Norris snorts battery acid to get a buzz. He claims it tickles.'),
(NULL,'Every time Chuck Norris executes a roundhouse kick, the incredible speed at which his leg cuts through the air creates an enormous sonic boom. This is commonly known as '),
(NULL,'When on vacation in December of 04 Chuck Norris was stung by a jelly fish. Delirious with rage at the unadulterated insolence, he roundhouse kicked the ocean into submission. The result nearly wiped out a generation of Thais.   '),
(NULL,'Chuck Norris chiseled the image of Mount Rushmore into his abs with a butter knife.'),
(NULL,'When Chuck Norris bleeds, oak trees sprout up from where the blood fell.'),
(NULL,'Chuck Norris puts the I in Team'),
(NULL,'Chuck Norris promised a Gypsy that he would eat San Francisco when Duke Nukem Forever is released. Thats why it has been pushed back so many times.'),
(NULL,'Chuck Norris was the inspiration for Donkey Kong, HD-TV, and waterslides. Yes, waterslides.'),
(NULL,'Once, while traveling in space, a stray asteroid collided with Chuck Norris testicles, slicing the left one off. Just to prove that hes badass, he ejaculated with only one testicle to stop the testicle that he didnt have. This event is recreated  in the end of Final Fantasy VII.'),
(NULL,'Chuck Norris knows how to pronounce Cthulhu. However, if he says Cthulhu in the correct pronounciation, several Turkmenistanian virgins will be sacrificed to Loki.'),
(NULL,'Chuck Norris can penetrate a female from up to a mile away, not psychokinetically, he just has a very large cock.'),
(NULL,'Chuck Norris once shot a German plane down with his finger by pointing at it and yelling, '),
(NULL,'Chuck Norris likes Pina Coladas, but fucking hates getting caught in the rain.'),
(NULL,'One time, Chuck Norris escaped from Alcatraz with nothing but an elastic band and a plastic fork. This was was the inspiration for the song '),
(NULL,'Scientology is Chuck Norris first sucessful get-rich-quick scheme.'),
(NULL,'Chuck Norris loves the smell of naplam in the morning.'),
(NULL,'Chuck Norris knows exactly where Waldo is on every page. Even the pirate one.'),
(NULL,'Chuck Norris once ate a whole cheesewheel to show a group of third graders how badass he is.'),
(NULL,'Chuck Norris went on a drug trip with Raffi, which resulted in the lyrics for the song '),
(NULL,'Once a grizzly bear threatened to eat Chuck Norris. Chuck showed the bear his fist and the bear proceeded to eat himself, because it would be the less painful way to die.'),
(NULL,'Chuck Norris let the dogs out. He has yet released a public apology for his actions.'),
(NULL,'Chuck Norris believes that a flamethrower is an essential part of a well balanced breakfast.'),
(NULL,'The two atomic bombs dropped on Japan in World War Two were actually two small parts of Chuck Norris left testicle, which he graciously donated to defeat Hitler and the Axis powers in 1943. Since then he has regenerated said testicle, and in the process made Tim McGraw a bigger douche.'),
(NULL,'Chuck Norris eats members of the Ku Klux Klan for lunch every Thursday.'),
(NULL,'Chuck Norris shot the sheriff AND the deputy. He then occupied the position of deputy.'),
(NULL,'Chuck Norris caught all 386 pokemon in just under 2.7 seconds. He says he wont trade any of them for anything.'),
(NULL,'One does not punch Chuck Norris; Chuck Norris headbutts ones fist.'),
(NULL,'Chuck Norris will kick you, and it will hurt. Forever.'),
(NULL,'Chuck Norris can stop time for up to two hours by thinking about pineapples'),
(NULL,'Chuck Norris punched a woman in the vagina when she didnt give him exact change.'),
(NULL,'If you shoot Chuck Norris, youll only make him angry.'),
(NULL,'Chuck Norris once destroyed Tokyo for fun, but was able to rebuild it in a matter of milliseconds.'),
(NULL,'Chuck Norris starts his day with a bowl of oatmeal, some pancakes and a glass of fresh squeezed Nazi juice.'),
(NULL,'Chuck Norris once fought off 42 ninjas bilndfolded, while having sex with 3 women.'),
(NULL,'After much debate, President Truman decided to drop the atomic bomb on Hiroshima rather than the alternative of sending Chuck Norris. His reasoning? It was more '),
(NULL,'Chuck Norris built the entire continent of Asia in two days using just a spoon and Teen People magazine.'),
(NULL,'Every piece of furniture in Chuck Norris house is a Total Gym.'),
(NULL,'Chuck Norris and Snoop Dogg once had a free style rap battle so awsome that people now celebrate the holiday Easter to remember the day.'),
(NULL,'Shortly after Bruce Lees death, Chuck Norris worked as a Chemist, during which time he discovered the element of surprise and later, painium. He won a nobel prize for his work which he put next to his imaginary Oscar on his trophy shelf'),
(NULL,'Chuck Norris has killed every single person who has ever called him '),
(NULL,'Halloween was invented when Chuck Norris disguised himself as a ghost so that he could beat up a pumpkin, light it on fire, and steal all of its candy.'),
(NULL,'Chuck Norris, when clean-shaven, radiates the heat of three suns.'),
(NULL,'The Internet slang Motts apple juice originally started as an inside joke between Chuck Norris and his invisible friend. His invisible friend bet him that he couldnt urinate into bottles and sell it to people.'),
(NULL,'Chuck Norris can play the solo from '),
(NULL,'Chuck Norris invented the cure for polio when he was bored one day.'),
(NULL,'If you take Chuck Norris and subtract the letters i, s, o, r, n, u, c, k, and h, then add the letters j, e, s, u, and s--in that order--you end up with Jesus.'),
(NULL,'Chuck Norris is what Willis is talkin bout.'),
(NULL,'The lead role for The Pacifier was chosen all depending on a game of Counter-Strike between Vin Diesel and Chuck Norris. Vin Diesel won the game, but only because he was camping. In an angered state of rage, Chuck Norris notified God and got Vin Diesel banned from Earth. That took him down a peg.'),
(NULL,'Chuck Norris knows whether the moon landings were fake or not.'),
(NULL,'Chuck Norris was the first person to tame a dinosaur.');
(NULL,'Chuck Norris isn\'t laughing. He knows you\'re trying to hack him.');
UNLOCK TABLES;
